name: Triger My Personal Website Bulid Action

on:
  push:
    branches:
      - main

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: send triger message
      run: |
        -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/dekuofa1995/dekuofa1995.github.io/dispatches \
        -d '{"event_type":"publish"}'
